kind = "web"
previewPath = "/"
title = "BagHunter"
version = "1.0.0"
id = "artifacts/treasure-hunt"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22584

[services.development]
run = "pnpm --filter @workspace/treasure-hunt run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/treasure-hunt", "run", "build" ]
publicDir = "artifacts/treasure-hunt/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22584"
BASE_PATH = "/"
